### ISSUE TITLE
Verify app

### ISSUE THREAD

**Issue by ovari** [flathub/org.moneymanagerex.MMEX#3]
It would be great to have this app as a verified app on [Flathub](https://flathub.org/apps/org.moneymanagerex.MMEX).

Can this app please be [verified on Flathub](https://flathub-docs.vercel.app/docs/for-users/verification)?

Is @joshua-stone a "third party approved by the developer"?

Or does @vomikan, or someone else on the MMEX team, need to do something like provide an [email address](https://github.com/moneymanagerex/moneymanagerex/issues/4313#issuecomment-1172470047)?

Thank you

**Comment by vomikan** [comment]
we have moneymanagerex@gmail.com address for that

**Comment by vomikan** [comment]
> Are you able to find [MMEX in the developer settings](https://flathub.org/apps/manage/org.moneymanagerex.MMEX) using the steps here?

Whoops!
You are unauthorized to view this content.

You might want to retry or go back [home](https://flathub.org/).

**Comment by ovari** [comment]
@Erick555 can you please help? Thank you

**Comment by ovari** [comment]
Merge request https://github.com/moneymanagerex/moneymanagerex/pull/5976 adds moneymanagerex@gmail.com email address to the upstream file. Hopefully that will enable verification.

**Comment by ovari** [comment]
> > Are you able to find [MMEX in the developer settings](https://flathub.org/apps/manage/org.moneymanagerex.MMEX) using the steps here?
> 
> Whoops! You are unauthorized to view this content.
> 
> You might want to retry or go back [home](https://flathub.org/).

@razzeee can you please help? Thank you

**Comment by razzeee** [comment]
I can't change rights, best would be to create an issue over at flathub/flathub

**Comment by ovari** [comment]
@joshua-stone can you start the verification process and then @vomikan can add a file like shown at https://github.com/flathub/eu.betterbird.Betterbird/issues/80#issuecomment-1578146333 ?

**Comment by joshua-stone** [comment]
@ovari @vomikan 

```
Create a page at https://moneymanagerex.org/.well-known/org.flathub.VerifiedApps.txt containing the following token:
c5cae2cc-d464-48c8-8e5e-693f2c30ea6d
If the page already exists, add the token to it.
```

**Comment by ovari** [comment]
Sorry, don't know where the website is located. Hopefully @vomikan can add what you require.

@joshua-stone are you able to update the Flathub listing as the AppData has been updated upstream.

Thank you

**Comment by joshua-stone** [comment]
The metainfo file has been updated in the flathub repo. It should eventually be installed during the build process so that it doesn't have to resides in the flathub repo anymore.

Is there anyone with admin access able to place the token at `https://moneymanagerex.org/.well-known/org.flathub.VerifiedApps.txt`? I believe that's the only blocker for this issue.

**Comment by whalley** [comment]
The token should be there now.
