### ISSUE TITLE
Set default permission to allow access to all storage

### ISSUE THREAD

**Issue by ovari** [flathub/org.moneymanagerex.MMEX#9]
Please set the default permission to allow access to all storage (e.g. USB, external, network).

1. [deb](https://app.circleci.com/pipelines/github/moneymanagerex/moneymanagerex/810/workflows/0beaf7a8-e325-4396-92d1-08bdc4715dcf/jobs/806/artifacts) version can access USB storage.
![deb](https://github.com/flathub/org.moneymanagerex.MMEX/assets/17465872/382e9d2a-5d75-4ba1-ad45-2dcc13a1e7bf)
2. [flatpak](https://flathub.org/apps/org.moneymanagerex.MMEX) version can not access USB storage.
![flatpak](https://github.com/flathub/org.moneymanagerex.MMEX/assets/17465872/73cb8e3c-6bb5-4371-802c-6e376c0af8f9)

Perhaps [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) could help with determining what settings are required and providing code pointers.

Thank you

**Comment by joshua-stone** [comment]
As shown here, you may have to add permissions to additional directories:

https://github.com/flathub/md.obsidian.Obsidian/blob/6b2b94ec8a124dee587058eb7cc9b3f59aaa0eae/md.obsidian.Obsidian.yml#L22

Please check to see which directories you add fix the issue, then create a pull request.

Thanks.

**Comment by ovari** [comment]
Sorry, can not check as we only provide patches using the web-browser.

Can all the permissions added in Obsidian be added to MMEX?

Thank you
